#!/bin/bash
# Example usage script for Pinterest scraper

echo "=== Pinterest Scraper Example Usage ==="
echo ""
echo "Before running this script, ensure you have:"
echo "1. Installed dependencies: pip install -r requirements.txt"
echo "2. Installed Playwright browsers: playwright install chromium"
echo ""
echo "Example commands:"
echo ""
echo "# Basic usage - search for 'nature photography' and download 10 images"
echo "python3 pinterest_scraper.py --keywords 'nature photography' --count 10"
echo ""
echo "# Search for multiple keywords"
echo "python3 pinterest_scraper.py --keywords 'mountains,sunset,landscape' --count 15"
echo ""
echo "# Custom output directory with higher rate limit"
echo "python3 pinterest_scraper.py --keywords 'design inspiration' --count 20 --output custom_images/ --rate-limit 3.0"
echo ""
echo "# Run with visible browser (for debugging)"
echo "python3 pinterest_scraper.py --keywords 'food photography' --count 5 --headless false"
echo ""
echo "=== End of Examples ==="
