#!/bin/bash
# Example usage script for Image Analyzer

echo "=== Image Analyzer Example Usage ==="
echo ""
echo "Before running this script, ensure you have:"
echo "1. Installed dependencies: pip install -r requirements.txt"
echo "2. Installed Tesseract OCR (see README.md for installation instructions)"
echo ""
echo "Example commands:"
echo ""
echo "# Basic usage - analyze images and output to JSON"
echo "python3 image_analyzer.py --input pinterest_images/ --output results.json"
echo ""
echo "# Export to both JSON and CSV"
echo "python3 image_analyzer.py --input images/ --output analysis.json --format both"
echo ""
echo "# Use GPU acceleration (if available)"
echo "python3 image_analyzer.py --input images/ --output results.json --gpu"
echo ""
echo "=== Complete Workflow Example ==="
echo ""
echo "# Step 1: Scrape Pinterest images"
echo "python3 pinterest_scraper.py --keywords 'digital art' --count 20 --output scraped_images/"
echo ""
echo "# Step 2: Analyze the scraped images"
echo "python3 image_analyzer.py --input scraped_images/ --output analysis_results.json --format both"
echo ""
echo "=== End of Examples ==="
